version: '3.8'

services:
  mcp-cci:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8050
    ports:
      - "8050:8050"
    environment:
      - HOST=0.0.0.0
      - PORT=8050
      - TRANSPORT=sse
    volumes:
      # Mount a volume for the devenv if you want persistence
      - ./devenv:/app/devenv
    restart: unless-stopped
    container_name: mcp-cci-server