version: '3.8'

services:
  sfcore-th-dev:
    image: ghcr.io/jorgesolebur/mcp-sfcore-th-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8050
    ports:
      - "8050:8050"
    environment:
      - HOST=0.0.0.0
      - PORT=8050
      - TRANSPORT=sse
    # volumes:
      # No volumes needed for direct CCI operation
    restart: unless-stopped
    container_name: sfcore-th-dev-server