[project]
name = "sfcore-th-dev"
version = "0.1.0"
description = "SFCore TH Dev - MCP server for CumulusCI CLI operations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "aiofiles>=23.1.0"
]
